syntax enable
colorscheme monokai

set expandtab
set smarttab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent
set number

filetype on
filetype plugin indent on

autocmd BufWritePre * %s/\s\+$//e

